# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 515)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(22, 23, 766, 435))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_openedImage = QtWidgets.QLabel(self.widget)
        self.label_openedImage.setMinimumSize(QtCore.QSize(400, 0))
        self.label_openedImage.setObjectName("label_openedImage")
        self.horizontalLayout.addWidget(self.label_openedImage)
        self.pushButton_openImage = QtWidgets.QPushButton(self.widget)
        self.pushButton_openImage.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_openImage.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_openImage.setObjectName("pushButton_openImage")
        self.horizontalLayout.addWidget(self.pushButton_openImage)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_class = QtWidgets.QLabel(self.widget)
        self.label_class.setMinimumSize(QtCore.QSize(100, 0))
        self.label_class.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_class.setObjectName("label_class")
        self.horizontalLayout.addWidget(self.label_class)
        self.pushButton_classify = QtWidgets.QPushButton(self.widget)
        self.pushButton_classify.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_classify.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_classify.setObjectName("pushButton_classify")
        self.horizontalLayout.addWidget(self.pushButton_classify)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_showImage = QtWidgets.QLabel(self.widget)
        self.label_showImage.setMinimumSize(QtCore.QSize(500, 400))
        self.label_showImage.setMaximumSize(QtCore.QSize(500, 400))
        self.label_showImage.setText("")
        self.label_showImage.setObjectName("label_showImage")
        self.horizontalLayout_4.addWidget(self.label_showImage)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_4.addWidget(self.textBrowser)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuExit.addAction(self.actionExit)
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_openedImage.setText(_translate("MainWindow", "暂无图片"))
        self.pushButton_openImage.setText(_translate("MainWindow", "打开图片"))
        self.label_class.setText(_translate("MainWindow", "未检测"))
        self.pushButton_classify.setText(_translate("MainWindow", "检测类别"))
        self.menuExit.setTitle(_translate("MainWindow", "Menu"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
